# https://docs.aws.amazon.com/codedeploy/latest/userguide/application-revisions-appspec-file.html#add-appspec-file-server

version: 0.0
os: windows

hooks:
  ApplicationStop:
    - location: AppStop\bin\Release\AppStop.exe
  ApplicationStart:
    - location: AppStart\bin\Release\AppStart.exe

# Other events we can use:
#  BeforeInstall (after ApplicationStop)
#  AfterInstall (after BeforeInstall)
#  ValidateService (after ApplicationStart)
