# https://docs.aws.amazon.com/codedeploy/latest/userguide/application-revisions-appspec-file.html#add-appspec-file-server

version: 0.0
os: windows

#files:
#  - source: RoosterBot\bin\Debug
#    destination: C:\temp\RoosterBot

hooks:
  ApplicationStop:
    - location: AppStop\bin\Debug\AppStop.exe
#  BeforeInstall:
#    - location: 
#  AfterInstall:
#    - location: 
  ApplicationStart:
    - location: appstart.cmd
      timeout: 10
#  ValidateService:
#   - location: 

