version: 0.2

env:
  variables:
    SOLUTION: .\RoosterBot.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.6.2
    
phases:
  build:
    commands:
      - '& "C:\ProgramData\chocolatey\bin\NuGet.exe" restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" -m -p:Configuration=Release -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION'

artifacts:
  files:
    - .\RoosterBot\bin\Release\*
    - .\AppStart\bin\Release\*
    - .\AppStop\bin\Release\*
    - appspec.yml
