version: 0.2

env:
  variables:
    SOLUTION: .\RoosterBot.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.6.2
    
phases:
  pre_build:
    commands:
      - 'dir "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework"'
  build:
    commands:
      - '& "C:\ProgramData\chocolatey\bin\NuGet.exe" restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" -m -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION'

artifacts:
  files:
    # CodeBuild for some reason always makes a debug build rather than a release build. Haven't figured out a way to fix this.
    - .\RoosterBot\bin\Debug\*
    - .\AppStart\bin\Debug\*
    - .\AppStop\bin\Debug\*
    - appspec.yml
