using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CsvHelper;
using RoosterBot;

namespace ScheduleComponent.Services {
	public class TeacherNameService {
		private List<TeacherInfo> m_Records = new List<TeacherInfo>();

		/// <summary>
		/// Clears all records.
		/// </summary>
		public void Reset() {
			m_Records.Clear();
		}

		/// <summary>
		/// Loads a CSV with teacher abbreviations into memory.
		/// </summary>
		public async Task ReadAbbrCSV(string path) {
			Logger.Log(Discord.LogSeverity.Info, "TeacherNameService", $"Loading abbreviation CSV file {Path.GetFileName(path)}");

			using (StreamReader reader = File.OpenText(path)) {
				using (CsvReader csv = new CsvReader(reader, new CsvHelper.Configuration.Configuration() { Delimiter = "," })) {
					await csv.ReadAsync();
					csv.ReadHeader();

					List<TeacherInfo> currentRecords = new List<TeacherInfo>();

					while (await csv.ReadAsync()) {
						TeacherInfo record = new TeacherInfo() {
							Abbreviation = csv["Abbreviation"],
							FullName = csv["FullName"],
							NoLookup = bool.Parse(csv["NoLookup"]),
							DiscordUser = csv["DiscordUser"]
						};
						string altSpellingsString = csv["AltSpellings"];

						if (altSpellingsString != "") {
							record.AltSpellings = altSpellingsString.Split(',');
						};

						currentRecords.Add(record);
					}

					lock (m_Records) {
						m_Records.AddRange(currentRecords);
					}
				}
			}
			Logger.Log(Discord.LogSeverity.Info, "TeacherNameService", $"Successfully loaded abbreviation CSV file {Path.GetFileName(path)}");
		}

		public TeacherInfo GetRecordFromAbbr(string abbr) {
			return m_Records.Find(record => record.Abbreviation == abbr);
		}

		public TeacherInfo[] GetRecordsFromAbbrs(string[] abbrs) {
			List<TeacherInfo> records = new List<TeacherInfo>();
			for (int i = 0; i < abbrs.Length; i++) {
				TeacherInfo record = GetRecordFromAbbr(abbrs[i]);
				if (record != null) {
					records.Add(record);
				}
			}
			return records.ToArray();
		}
		
		public TeacherInfo[] Lookup(string nameInput, bool skipNoLookup = true) {
			nameInput = nameInput.ToLower();

			List<TeacherInfo> records = new List<TeacherInfo>();

			foreach (TeacherInfo record in m_Records) {
				if (skipNoLookup && record.NoLookup)
					continue;

				if (record.MatchName(nameInput)) {
					records.Add(record);
				}
			}
			
			return records.ToArray();
		}
		
		public IReadOnlyList<TeacherInfo> GetAllRecords() {
			return m_Records as IReadOnlyList<TeacherInfo>;
		}
	}

	public class TeacherInfo : IdentifierInfo {
		public string	Abbreviation;
		public string	FullName;
		public string[] AltSpellings;
		public bool		NoLookup;
		public string	DiscordUser;

		public bool MatchName(string nameInput) {
			// We match the input by first checking if their full name starts with the input (case insensitive),
			//  and then by checking if the *input* starts with one of the alternative spellings (also case insensitive).

			// Check start of full name or exact match with abbreviation
			if (Abbreviation.ToLower() == nameInput ||
				FullName.ToLower().StartsWith(nameInput)) {
				return true;
			} else if (AltSpellings != null) {
				// Check alternative spellings
				foreach (string altSpelling in AltSpellings) {
					if (nameInput.StartsWith(altSpelling)) {
						return true;
					}
				}
			}
			return false;
		}

		public override string TypeName => "StaffMember";
		public override string ScheduleCode => Abbreviation;
		public override string DisplayText => FullName;

		public override bool Matches(ScheduleRecord record) {
			return record.StaffMember.Contains(this);
		}

		public override bool Equals(object obj) {
			// Auto-generated by Visual Studio 2017
			var info = obj as TeacherInfo;
			return info != null &&
				   //base.Equals(obj) && // produces compile error
				   this.Abbreviation == info.Abbreviation &&
				   this.FullName == info.FullName &&
				   EqualityComparer<string[]>.Default.Equals(this.AltSpellings, info.AltSpellings) &&
				   this.NoLookup == info.NoLookup &&
				   this.DiscordUser == info.DiscordUser;
		}

		public override int GetHashCode() {
			// Auto-generated by Visual Studio 2017
			var hashCode = 197285817;
			//hashCode = hashCode * -1521134295 + base.GetHashCode(); // produces compile error
			hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(this.Abbreviation);
			hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(this.FullName);
			hashCode = hashCode * -1521134295 + EqualityComparer<string[]>.Default.GetHashCode(this.AltSpellings);
			hashCode = hashCode * -1521134295 + this.NoLookup.GetHashCode();
			hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(this.DiscordUser);
			return hashCode;
		}
	}
}
